ageAbove18 = "1"
gender = "1"
pinCode = "12345"
revealAgeAbove18 = "1"
revealGender = "1"
revealPinCode = "1"
revealState = "1"
state = "42"

[qrDataExtractor]
ageAbove18 = "1"
gender = "1"
pinCode = "12345"
state = "42"
